# Generated by Django 3.0.2 on 2020-02-19 09:50

import device.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20200219_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[device.models.mycustomvalidator, device.models.val2]),
        ),
    ]
